### ISSUE TITLE
Request and bug in P.Values in glMDPlot

### ISSUE THREAD

**Issue by jdrnevich** [Shians/Glimma#139]
I'd like to request that raw P.Values as well as adj.P.Vals are automatically output in the bottom table of glMDPlot(). I've been able to add raw P.Values by adding them in the anno argument, but when I did I noticed a bug because sorting by P.Value vs. adj.P.Vals did not give the same gene order. Looking further, it appears that p-values between 1e-05 and 5e-05 get rounded to 0, but p-values < 1e-05 get rounded to 5 significant digits (e-06 are shown as 0.0000010481 whereas < e-07 are shown as 9.8143e-7) while p-values > 5e-05 get rounded to 4 decimal places (0.0001). Probably anything > 1e-05 is getting rounded to 4 decimal places which is why those > 5e-05 get rounded to 0. Can this be fixed so they are all rounded to the same number of significant digits to maintain significance order?

Thanks!
Jenny

**Comment by Shians** [comment]
This has actually been fixed in #124 and if you use `devtools::install_github("shians/Glimma")` you should be able to use a fixed version. There's some issues with my vignette which makes me reluctant to push all my fixes up to Bioconductor, hopefully I'll have it sorted soon.

I'm not keen to keep in P values because those are misleading in multiple testing situations. You can always stick it in intentionally via a column if you know what you want.

**Comment by jdrnevich** [comment]
Thanks - I downloaded the github version, but it was hard to tell if the p-value rounding issue was fixed because there are now other problems with the table - I'll detail in another issue
